package school.service;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.function.Consumer;

/**
 * Part 27 - Multithreading demonstration for the School Management System.
 *
 * Demonstrates:
 * - Thread
 * - Runnable
 * - ExecutorService
 * - fixed thread pool
 * - synchronization
 * - concurrent collection
 * - background report generation, record processing and database backup
 */
public final class BackgroundTaskService {

    private static final ExecutorService EXECUTOR = Executors.newFixedThreadPool(3);
    private static final ConcurrentLinkedQueue<String> TASK_HISTORY = new ConcurrentLinkedQueue<>();
    private static final DateTimeFormatter DISPLAY_TIME = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private static final DateTimeFormatter FILE_TIME = DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss-SSS");

    private BackgroundTaskService() {
    }

    /**
     * synchronized is intentionally used here to demonstrate synchronized access
     * while the history itself is also stored in a thread-safe concurrent collection.
     */
    private static synchronized void recordHistory(String message) {
        TASK_HISTORY.add(LocalDateTime.now().format(DISPLAY_TIME) + " | " + message);
        while (TASK_HISTORY.size() > 200) {
            TASK_HISTORY.poll();
        }
    }

    private static void publish(Consumer<String> listener, String message) {
        recordHistory(message);
        if (listener != null) {
            listener.accept(message);
        }
    }

    public static List<String> getHistorySnapshot() {
        return new ArrayList<>(TASK_HISTORY);
    }

    /** Demonstrates creating a Runnable and starting it with Thread directly. */
    public static void runThreadDemo(Consumer<String> listener) {
        Runnable task = () -> {
            String threadName = Thread.currentThread().getName();
            publish(listener, "Thread/Runnable demo started on " + threadName + ".");
            try {
                Thread.sleep(700);
                publish(listener, "Thread/Runnable demo completed on " + threadName + ".");
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                publish(listener, "Thread/Runnable demo was interrupted.");
            }
        };

        Thread thread = new Thread(task, "school-thread-demo");
        thread.start();
    }

    /** Demonstrates ExecutorService + thread pool + background file generation. */
    public static void generateReportAsync(Consumer<String> listener) {
        Runnable reportTask = () -> {
            publish(listener, "Background report generation started on " + Thread.currentThread().getName() + ".");
            try {
                Path directory = Path.of("reports");
                Files.createDirectories(directory);
                Path reportFile = directory.resolve(
                    "background-report-" + LocalDateTime.now().format(FILE_TIME) + ".txt"
                );

                int students;
                int teachers;
                int courses;
                int enrollments;
                int results;
                int attendance;
                int payments;

                try (Connection connection = StudentDatabase.connect()) {
                    students = count(connection, "students");
                    teachers = count(connection, "teachers");
                    courses = count(connection, "courses");
                    enrollments = count(connection, "enrollments");
                    results = count(connection, "results");
                    attendance = count(connection, "attendance");
                    payments = count(connection, "payments");
                }

                String text = """
                    SCHOOL MANAGEMENT SYSTEM - BACKGROUND REPORT
                    =============================================
                    Total Students: %d
                    Total Teachers: %d
                    Total Courses: %d
                    Total Enrollments: %d
                    Total Results: %d
                    Attendance Records: %d
                    Payment Records: %d

                    Generated by: %s
                    """.formatted(
                        students, teachers, courses, enrollments,
                        results, attendance, payments,
                        Thread.currentThread().getName()
                    );

                Files.writeString(reportFile, text, StandardCharsets.UTF_8);
                publish(listener, "Background report saved to " + reportFile.toAbsolutePath() + ".");
            } catch (SQLException | IOException e) {
                publish(listener, "Background report failed: " + e.getMessage());
            }
        };

        EXECUTOR.submit(reportTask);
    }

    /** Demonstrates processing a potentially large result set away from the Swing UI thread. */
    public static void processStudentRecordsAsync(Consumer<String> listener) {
        EXECUTOR.submit(() -> {
            publish(listener, "Student record processing started on " + Thread.currentThread().getName() + ".");
            int processed = 0;

            String sql = "SELECT student_id, first_name, last_name FROM students ORDER BY student_id";
            try (Connection connection = StudentDatabase.connect();
                 Statement statement = connection.createStatement();
                 ResultSet result = statement.executeQuery(sql)) {

                while (result.next()) {
                    processed++;
                    String id = result.getString("student_id");
                    String name = result.getString("first_name") + " " + result.getString("last_name");
                    publish(listener, "Processed student " + id + " - " + name + ".");

                    try {
                        Thread.sleep(120);
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                        publish(listener, "Student processing interrupted after " + processed + " record(s).");
                        return;
                    }
                }

                publish(listener, "Student record processing completed. Total processed: " + processed + ".");
            } catch (SQLException e) {
                publish(listener, "Student processing failed: " + e.getMessage());
            }
        });
    }

    /**
     * Creates an H2 SQL backup using H2's SCRIPT command on a background thread.
     * This avoids copying a live database file directly.
     */
    public static void createDatabaseBackupAsync(Consumer<String> listener) {
        EXECUTOR.submit(() -> {
            publish(listener, "Database backup started on " + Thread.currentThread().getName() + ".");
            try {
                Path directory = Path.of("backups");
                Files.createDirectories(directory);
                Path backup = directory.resolve(
                    "school-backup-" + LocalDateTime.now().format(FILE_TIME) + ".sql"
                ).toAbsolutePath().normalize();

                String safePath = backup.toString().replace("\\", "/").replace("'", "''");
                try (Connection connection = StudentDatabase.connect();
                     Statement statement = connection.createStatement()) {
                    statement.execute("SCRIPT TO '" + safePath + "'");
                }

                publish(listener, "Database backup created at " + backup + ".");
            } catch (SQLException | IOException e) {
                publish(listener, "Database backup failed: " + e.getMessage());
            }
        });
    }

    /** Demonstrates several independent jobs sharing the fixed-size thread pool. */
    public static void runThreadPoolDemo(Consumer<String> listener) {
        for (int taskNumber = 1; taskNumber <= 3; taskNumber++) {
            final int number = taskNumber;
            EXECUTOR.submit(() -> {
                String name = Thread.currentThread().getName();
                publish(listener, "Thread-pool task " + number + " started on " + name + ".");
                try {
                    Thread.sleep(500L + (number * 150L));
                    publish(listener, "Thread-pool task " + number + " finished on " + name + ".");
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    publish(listener, "Thread-pool task " + number + " was interrupted.");
                }
            });
        }
    }

    private static int count(Connection connection, String table) throws SQLException {
        // Table name is chosen only from hard-coded application values above, never user input.
        try (Statement statement = connection.createStatement();
             ResultSet result = statement.executeQuery("SELECT COUNT(*) FROM " + table)) {
            return result.next() ? result.getInt(1) : 0;
        }
    }
}
