package school.service;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.*;

class AuthServiceTest {

    private static final char[] TEST_PASSWORD =
        "JUnitPassword123!".toCharArray();

    @BeforeAll
    static void setUpDatabase() throws Exception {
        System.setProperty(
            "school.db.url",
            "jdbc:h2:mem:school_auth_test;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE"
        );

        try (Connection connection = StudentDatabase.connect();
             Statement statement = connection.createStatement()) {

            statement.execute("DROP TABLE IF EXISTS users");
            statement.execute("""
                CREATE TABLE users (
                    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(100) UNIQUE NOT NULL,
                    password_hash VARCHAR(500) NOT NULL,
                    role VARCHAR(50) NOT NULL
                )
                """);
        }

        AuthService.createAdmin(TEST_PASSWORD.clone());
    }

    @Test
    void validAdministratorLoginSucceeds() throws Exception {
        assertTrue(
            AuthService.login("admin", TEST_PASSWORD.clone())
        );
    }

    @Test
    void wrongPasswordLoginFails() throws Exception {
        assertFalse(
            AuthService.login(
                "admin",
                "WrongPassword123!".toCharArray()
            )
        );
    }

    @Test
    void unknownUserLoginFails() throws Exception {
        assertFalse(
            AuthService.login(
                "nobody",
                TEST_PASSWORD.clone()
            )
        );
    }
}
