-- School Management System - H2 Schema
-- The embedded H2 database file is created automatically by the JDBC URL:
-- jdbc:h2:./data/school;DATABASE_TO_LOWER=TRUE

CREATE TABLE IF NOT EXISTS departments (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS classes (
    class_id VARCHAR(50) PRIMARY KEY,
    class_name VARCHAR(150) NOT NULL,
    department_id INTEGER,
    level INTEGER NOT NULL,
    FOREIGN KEY (department_id) REFERENCES departments(department_id)
);

CREATE TABLE IF NOT EXISTS students (
    student_id VARCHAR(50) PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    gender VARCHAR(30),
    date_of_birth VARCHAR(20),
    email VARCHAR(255) UNIQUE,
    phone VARCHAR(50),
    department_id INTEGER,
    level INTEGER,
    FOREIGN KEY (department_id) REFERENCES departments(department_id)
);

CREATE TABLE IF NOT EXISTS teachers (
    teacher_id VARCHAR(50) PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE,
    department_id INTEGER,
    FOREIGN KEY (department_id) REFERENCES departments(department_id)
);

CREATE TABLE IF NOT EXISTS courses (
    course_id VARCHAR(50) PRIMARY KEY,
    course_name VARCHAR(200) NOT NULL,
    department_id INTEGER,
    teacher_id VARCHAR(50),
    FOREIGN KEY (department_id) REFERENCES departments(department_id),
    FOREIGN KEY (teacher_id) REFERENCES teachers(teacher_id)
);

CREATE TABLE IF NOT EXISTS examinations (
    exam_id VARCHAR(50) PRIMARY KEY,
    course_id VARCHAR(50) NOT NULL,
    exam_name VARCHAR(150) NOT NULL,
    exam_date VARCHAR(20) NOT NULL,
    FOREIGN KEY (course_id) REFERENCES courses(course_id)
);

CREATE TABLE IF NOT EXISTS enrollments (
    student_id VARCHAR(50) NOT NULL,
    course_id VARCHAR(50) NOT NULL,
    PRIMARY KEY (student_id, course_id),
    FOREIGN KEY (student_id) REFERENCES students(student_id),
    FOREIGN KEY (course_id) REFERENCES courses(course_id)
);

CREATE TABLE IF NOT EXISTS results (
    result_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(50) NOT NULL,
    course_id VARCHAR(50) NOT NULL,
    score DOUBLE PRECISION NOT NULL CHECK(score BETWEEN 0 AND 100),
    grade VARCHAR(10),
    FOREIGN KEY (student_id, course_id) REFERENCES enrollments(student_id, course_id)
);

CREATE TABLE IF NOT EXISTS payments (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(50) NOT NULL,
    amount DECIMAL(14,2) NOT NULL CHECK(amount > 0),
    payment_date VARCHAR(20) NOT NULL,
    payment_method VARCHAR(50),
    FOREIGN KEY (student_id) REFERENCES students(student_id)
);

CREATE TABLE IF NOT EXISTS attendance (
    attendance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(50) NOT NULL,
    course_id VARCHAR(50) NOT NULL,
    attendance_date VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    FOREIGN KEY (student_id, course_id) REFERENCES enrollments(student_id, course_id)
);

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(1024) NOT NULL,
    role VARCHAR(30) NOT NULL CHECK(role IN ('ADMIN', 'TEACHER', 'STUDENT', 'ACCOUNTANT'))
);

CREATE TABLE IF NOT EXISTS account_profiles (
    user_id INTEGER PRIMARY KEY,
    student_id VARCHAR(50) UNIQUE,
    teacher_id VARCHAR(50) UNIQUE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE RESTRICT,
    FOREIGN KEY (teacher_id) REFERENCES teachers(teacher_id) ON DELETE RESTRICT,
    CHECK (student_id IS NULL OR teacher_id IS NULL)
);
